<a href="https://colab.research.google.com/github/Clinton1029/Heart_prediction1/blob/main/Heart_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Heart Disease Prediction Using Machine Learning

## Project Overview

Heart disease is one of the leading causes of death worldwide. Early prediction of heart disease can help healthcare professionals provide timely treatment and improve patient outcomes. This project aims to develop a machine learning model capable of predicting whether a patient has heart disease based on various health indicators and lifestyle factors.

The dataset contains demographic information, medical history, lifestyle habits, and health conditions such as BMI, smoking status, alcohol consumption, physical activity, diabetes, and other risk factors.

The project follows the standard machine learning workflow from data loading to model deployment.

# Project Workflow

The project follows these major steps:

1. Import Required Libraries
2. Load the Dataset
3. Exploratory Data Analysis (EDA)
4. Data Preprocessing and Preparation
5. Feature Selection
6. Split the Dataset into Training and Testing Sets
7. Choose the Machine Learning Model
8. Train the Machine Learning Model
9. Make Predictions
10. Evaluate Model Performance
11. Hyperparameter Tuning
12. Predict Heart Disease for New Patients

# 1. Import Libraries

In [1]:

import os
import pandas as pd

# 2. Load the Data

In [6]:
# Define the path to your file
file_path = "/content/Heart Disease.xlsx"

# Check if the file exists
if os.path.exists(file_path):
    print("File exists! Loading with pandas...")

    # Load the CSV file
    df = pd.read_excel(file_path)

    print("\nDataset loaded successfully!")

else:
    print("FILE DOESN'T EXIST")

File exists! Loading with pandas...

Dataset loaded successfully!

# 3. Exploratory Data Analysis

### 3.1 Display the First Five Records

In [7]:
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3,30,No,Female,55-59,White,Yes,Yes,Very good,5,Yes,No,Yes
1,No,20.34,No,No,Yes,0,0,No,Female,80 or older,White,No,Yes,Very good,7,No,No,No
2,No,26.58,Yes,No,No,20,30,No,Male,65-69,White,Yes,Yes,Fair,8,Yes,No,No
3,No,24.21,No,No,No,0,0,No,Female,75-79,White,No,No,Good,6,No,No,Yes
4,No,23.71,No,No,No,28,0,Yes,Female,40-44,White,No,Yes,Very good,8,No,No,No

### 3.2 Display the Last Five Records

In [8]:
df.tail()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
319790,Yes,27.41,Yes,No,No,7,0,Yes,Male,60-64,Hispanic,Yes,No,Fair,6,Yes,No,No
319791,No,29.84,Yes,No,No,0,0,No,Male,35-39,Hispanic,No,Yes,Very good,5,Yes,No,No
319792,No,24.24,No,No,No,0,0,No,Female,45-49,Hispanic,No,Yes,Good,6,No,No,No
319793,No,32.81,No,No,No,0,0,No,Female,25-29,Hispanic,No,No,Good,12,No,No,No
319794,No,46.56,No,No,No,0,0,No,Female,80 or older,Hispanic,No,Yes,Good,8,No,No,No

### 3.3 Dataset Shape

The shape of the dataset provides the number of observations (rows) and features (columns). This helps us understand the size of the dataset before performing further analysis.

In [9]:
# Display the number of rows and columns
print("Dataset Shape:", df.shape)

Dataset Shape: (319795, 18)

### 3.4 Dataset Information

The dataset information provides a concise summary of the DataFrame, including the number of entries, column names, non-null values, and data types.

 It also helps identify missing values and understand the overall structure of the dataset.

In [10]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  int64
 6   MentalHealth      319795 non-null  int64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  int64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(1), int64(3), object(14)
memory usage: 43.9+ MB

### 3.5 Descriptive Statistics

Descriptive statistics summarize the numerical features of the dataset by providing measures such as count, mean, standard deviation, minimum, maximum, and quartiles. These statistics help us understand the distribution and variability of the data.

In [11]:
# Display descriptive statistics for numerical features
df.describe()

                 BMI  PhysicalHealth   MentalHealth      SleepTime
count  319795.000000    319795.00000  319795.000000  319795.000000
mean       28.325399         3.37171       3.898366       7.097075
std         6.356100         7.95085       7.955235       1.436007
min        12.020000         0.00000       0.000000       1.000000
25%        24.030000         0.00000       0.000000       6.000000
50%        27.340000         0.00000       0.000000       7.000000
75%        31.420000         2.00000       3.000000       8.000000
max        94.850000        30.00000      30.000000      24.000000

In [12]:
# Display descriptive statistics for categorical features
df.describe(include='object')

,HeartDisease,Smoking,AlcoholDrinking,Stroke,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,Asthma,KidneyDisease,SkinCancer
count,319795,319795,319795,319795,319795,319795,319795,319795,319795,319795,319795,319795,319795,319795
unique,2,2,2,2,2,2,13,6,4,2,5,2,2,2
top,No,No,No,No,No,Female,65-69,White,No,Yes,Very good,No,No,No
freq,292422,187887,298018,307726,275385,167805,34151,245212,269653,247957,113858,276923,308016,289976